# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bluebuild-fedora-atomic-niri
description: My custom Fedora Atomic image with Niri WM
base-image: ghcr.io/ublue-os/minimal
image-version: 44

modules:
  - type: rpm-ostree
    install:
      # Драйверы, Графика и Аппаратное ускорение AMD RX 6600
      - mesa-dri-drivers
      - vulkan-radeon
      - libva-utils

      # Базовое окружение Niri + Запуск
      - niri
      - uwsm
      - xwayland-satellite
      - waybar
      - fuzzel
      - mako
      - swaybg
      - hyprlock
      - hypridle
      - alacritty
      - wl-clipboard
      - adwaita-cursor-theme

      # Экран логина
      - greetd
      - tuigreet

      # Интеграция и Порталы
      - xdg-desktop-portal
      - xdg-desktop-portal-gnome
      - xdg-desktop-portal-gtk

      # Система, Звук и Авторизация
      - NetworkManager
      - NetworkManager-tui
      - iwd
      - firewalld
      - bluez
      - bluez-utils
      - pipewire
      - pipewire-pulse
      - wireplumber
      - pavucontrol
      - udiskie
      - udisks2
      - upower
      - brightnessctl
      - lxqt-policykit
      - gnome-keyring
      - libsecret

      # Контейнеры и Песочницы
      - podman
      - podman-docker
      - distrobox
      - flatpak

      # CLI-инструменты инфраструктуры
      - git
      - zsh
      - tmux
      - neovim
      - bat
      - eza
      - fzf
      - ripgrep
      - zoxide
      - btop
      - wget
      - zip
      - unzip
      - fd-find
      - git-delta
      - pass

      # Просмотрщики медиа и документов для Yazi
      - yazi
      - mpv
      - imv
      - zathura
      - zathura-pdf-mupdf
      - ffmpegthumbnailer
      - imagemagick
      - p7zip
      - unar
      - poppler-utils

      # Шрифты
      - google-noto-sans-fonts
      - google-noto-color-emoji-fonts
      - jetbrains-mono-fonts

  - type: systemd
    system:
      enabled:
        - greetd
        - NetworkManager
        - firewalld
        - bluetooth
