[terminal]
# Явно указываем виртуальный терминал (VT), на котором запустится экран входа
vt = 1

[default_session]
# Запускаем tuigreet. При успешном входе он передает управление в uwsm для старта Niri
command = "tuigreet --time --remember --remember-user --cmd 'uwsm start niri.desktop'"
user = "greeter"
